- name: Get facts about AWS
  hosts: all
  order: sorted
  become: True
  tasks:
   - name: install Python boto packages
     yum:
      name: "{{ item }}"
      with_items:
       - python2-boto3
       - python2-botocore
   - name: Get facts about VPC
     ec2_vpc_net_facts:
