---
- name: Install and Configure Nginx web Server
  hosts: all
  become: True
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: copy config file
      copy:
         src: files/nginx.conf
         dest: /etc/nginx/nginx.conf
         mode: 0644

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: restart nginx
      service:
          name: nginx
          enabled: yes
          state: restarted