---
- name: Windows servers
  hosts: all
  gather_facts: yes
  tasks:
   - name: windows get credentials
     win_whoami:
#
   - name: create group
     win_group:
       name: Developers
       description: Developers Group created by Ansible Tower
       state: present
#