- name: Enable EPEL repository and update all servers
  hosts: localhost
  order: sorted
  become: True
  tasks:
#   - name: Install EPEL7 Repository
#      yum:
#        name: 'epel-release'
#        state: latest
#
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest